name: Cloudflare Access SSH
description: Run a command on a remote host over SSH using Cloudflare Access (cloudflared access ssh).
inputs:
  host:
    description: SSH host (e.g. di4dtestssh.davidmaat.be)
    required: true
  username:
    description: SSH username
    required: true
  port:
    description: SSH port
    required: false
    default: "22"
  private_key:
    description: SSH private key contents (OpenSSH format)
    required: true
  cf_access_client_id:
    description: Cloudflare Access service token client id
    required: true
  cf_access_client_secret:
    description: Cloudflare Access service token client secret
    required: true
  command:
    description: Remote command to execute
    required: true
runs:
  using: composite
  steps:
    - name: Install cloudflared
      shell: bash
      run: |
        set -euo pipefail
        sudo curl -fsSL \
          https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 \
          -o /usr/local/bin/cloudflared
        sudo chmod +x /usr/local/bin/cloudflared

    - name: Configure SSH key
      shell: bash
      env:
        SSH_PRIVATE_KEY_VALUE: ${{ inputs.private_key }}
      run: |
        set -euo pipefail
        install -d -m 700 ~/.ssh
        printf '%s\n' "$SSH_PRIVATE_KEY_VALUE" | tr -d '\r' > ~/.ssh/id_deploy
        chmod 600 ~/.ssh/id_deploy
        ssh-keygen -y -f ~/.ssh/id_deploy >/dev/null

    - name: Run remote command
      shell: bash
      env:
        SSH_HOST: ${{ inputs.host }}
        SSH_PORT: ${{ inputs.port }}
        SSH_USERNAME: ${{ inputs.username }}
        CF_ACCESS_CLIENT_ID: ${{ inputs.cf_access_client_id }}
        CF_ACCESS_CLIENT_SECRET: ${{ inputs.cf_access_client_secret }}
        REMOTE_COMMAND: ${{ inputs.command }}
      run: |
        set -euo pipefail
        ssh \
          -i ~/.ssh/id_deploy \
          -o IdentitiesOnly=yes \
          -o StrictHostKeyChecking=no \
          -o UserKnownHostsFile=/dev/null \
          -o ProxyCommand="cloudflared access ssh --hostname %h" \
          -p "$SSH_PORT" \
          "$SSH_USERNAME@$SSH_HOST" \
          "$REMOTE_COMMAND"
