# Generated by Django 5.2.9 on 2026-01-08 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('zCode', models.CharField(max_length=50)),
                ('credits', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('phase', models.IntegerField()),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField()),
                ('location', models.CharField(max_length=200)),
                ('pageLink', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('isActive', models.BooleanField(default=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField()),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TechTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('thubnail', models.CharField()),
                ('videoPath', models.CharField()),
                ('isPublic', models.BooleanField(default=False)),
                ('speaker', models.CharField(max_length=100)),
                ('description', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField()),
                ('link', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('studentApplicationFormId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='DI4D_app.form')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryStudentApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('formId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='DI4D_app.form')),
            ],
        ),
        migrations.CreateModel(
            name='LearninggoalCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='DI4D_app.course')),
                ('learningGoalId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='DI4D_app.learninggoal')),
            ],
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='learningPath',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='DI4D_app.learningpath'),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='DI4D_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramLearningoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMandatory', models.BooleanField(default=False)),
                ('learningGoalId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='DI4D_app.learninggoal')),
                ('programId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='DI4D_app.program')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField()),
                ('contact', models.CharField()),
                ('timing', models.CharField()),
                ('technology', models.CharField()),
                ('workspace', models.CharField()),
                ('projectNumber', models.IntegerField()),
                ('publishDate', models.DateField()),
                ('scrumMaster', models.CharField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=True)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='DI4D_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField()),
                ('explanation', models.CharField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isMandatory', models.BooleanField(default=False)),
                ('datatype', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='DI4D_app.datatype')),
                ('formId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='DI4D_app.form')),
            ],
        ),
        migrations.CreateModel(
            name='UserLearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDone', models.BooleanField(default=False)),
                ('defence', models.CharField()),
                ('isVerified', models.BooleanField(default=False)),
                ('verifiedDate', models.DateField(blank=True, null=True)),
                ('learningGoalId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='DI4D_app.learninggoal')),
            ],
        ),
        migrations.CreateModel(
            name='UserLearningProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaPath', models.CharField()),
                ('userLearningGoalId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='DI4D_app.userlearninggoal')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profilePicture', models.CharField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('partnerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='DI4D_app.partner')),
                ('userTypeId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='DI4D_app.usertype')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserWebinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canEdit', models.BooleanField(default=False)),
                ('canGive', models.BooleanField(default=False)),
                ('webinarId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='DI4D_app.webinar')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTechTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canEdit', models.BooleanField(default=False)),
                ('techTalkId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='DI4D_app.techtalk')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settingJson', models.CharField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isInterrested', models.BooleanField(default=False)),
                ('isApproved', models.BooleanField(default=False)),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='DI4D_app.project')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userlearninggoal',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='studentId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlearninggoal',
            name='teacherId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='teacherId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canEdit', models.BooleanField(default=False)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='DI4D_app.event')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaPath', models.CharField()),
                ('isPublic', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('lastEditDate', models.DateField()),
                ('description', models.CharField()),
                ('showAuthor', models.BooleanField(default=False)),
                ('picture', models.CharField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField()),
                ('answerDate', models.DateField()),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='DI4D_app.question')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CommunicationUserLearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField()),
                ('publishDate', models.DateTimeField()),
                ('UserLearningGoalId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='DI4D_app.userlearninggoal')),
                ('publisherId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
