# Generated by Django 5.2.9 on 2026-01-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DI4D_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='picture',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
