# Generated by Django 5.2.9 on 2026-01-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DI4D_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_alumni',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
