# Generated by Django 5.2.9 on 2026-01-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DI4D_app', '0003_alter_user_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='techtalk',
            name='date',
            field=models.DateField(),
        ),
    ]
