# Generated by Django 5.2.9 on 2026-01-19 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DI4D_app', '0004_techtalk_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsetting',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationsetting',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationsetting',
            name='studentApplicationFormId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='DI4D_app.form'),
        ),
        migrations.AlterField(
            model_name='techtalk',
            name='date',
            field=models.DateField(),
        ),
    ]
