# Generated by Django 5.2.9 on 2026-01-23 10:12

import DI4D_app.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DI4D_app', '0006_question_content_alter_formanswer_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(default='', verbose_name='content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='mediaPath',
            field=models.CharField(default=DI4D_app.models.media_path_default, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(upload_to='news_pictures/'),
        ),
    ]
