# Generated by Django 5.2.9 on 2026-02-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DI4D_app', '0008_formanswer_submission_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusStudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='evaluate', max_length=50)),
                ('submission_number', models.IntegerField()),
            ],
        ),
    ]
