# Generated by Django 5.2.9 on 2026-02-11 10:09

import DI4D_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DI4D_app', '0008_formanswer_submission_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='mediaPath',
            field=models.CharField(default=DI4D_app.models.media_path_default, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(upload_to='news_pictures/'),
        ),
    ]
