# Generated by Django 5.2.9 on 2026-02-16 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DI4D_app', '0008_formanswer_submission_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isDeleted', models.BooleanField(default=False)),
                ('s3Link', models.CharField(unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='owned_file_items', to=settings.AUTH_USER_MODEL)),
                ('parentFolder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='DI4D_app.fileitem')),
            ],
        ),
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='DI4D_app.fileitem')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_file_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
