# Generated by Django 5.2.9 on 2026-02-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DI4D_app', '0009_news_content_alter_news_mediapath_alter_news_picture'),
        ('DI4D_app', '0009_seed_initial_data'),
        ('DI4D_app', '0009_statusstudentregistration'),
    ]

    operations = [
    ]
