# Generated by Django 5.2.9 on 2026-02-11 12:25

from django.db import migrations

def seed_initial_data(apps, schema_editor):
    # Get the models
    UserType = apps.get_model('DI4D_app', 'UserType')
    Country = apps.get_model('DI4D_app', 'Country')
    Partner = apps.get_model('DI4D_app', 'Partner')
    DataType = apps.get_model('DI4D_app', 'DataType')

    # Seed UserType
    user_types = ['admin', 'student', 'partner', 'sharepointuser']
    for user_type in user_types:
        UserType.objects.get_or_create(name=user_type)
    
    # Seed Country
    belgium, create = Country.objects.get_or_create(name='Belgium')
    cuba, create = Country.objects.get_or_create(name='Cuba')
    kenia, create = Country.objects.get_or_create(name='Kenia')
    tanzania, create = Country.objects.get_or_create(name='Tanzania')
    uganda, create = Country.objects.get_or_create(name='Uganda')
    ethiopia, create = Country.objects.get_or_create(name='Ethiopia')

    # Seed Partner
    partners = ['Thomas More', 'Cujae', 'Nairobi', 'Kirinyaga', 'Ardhi', 'Makerere', 'Mbarara', 'Mekelle', 'Hawassa', 'Addis Ababa']
    countrys = [belgium, cuba, kenia, kenia, tanzania, uganda, uganda, ethiopia, ethiopia,  ethiopia]
    citys = ['Geel', 'La Habana', 'Nairobi', 'Kerugoya', 'Dar es Salaam', 'Kampala', 'Mbara', 'Mekelle', 'Hawassa', 'Addis Ababa']
    for partner, country, city in zip(partners, countrys, citys):
        Partner.objects.get_or_create(name=partner, city=city, country=country)

    # Seed DataType
    data_types = ['Text', 'File', 'Multiple_Choice', 'Singular_Choice', 'Bool']
    for data_type in data_types:
        DataType.objects.get_or_create(name=data_type)


class Migration(migrations.Migration):

    dependencies = [
        ('DI4D_app', '0009_news_content_alter_news_mediapath_alter_news_picture'),
    ]

    operations = [
        migrations.RunPython(seed_initial_data),
    ]
