# Generated by Django 5.2.9 on 2026-02-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DI4D_app', '0010_seed_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
