# Generated by Django 5.2.9 on 2026-02-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DI4D_app', '0010_merge_20260218_1435'),
        ('DI4D_app', '0011_alter_form_enddate'),
    ]

    operations = [
    ]
