# Generated by Django 5.2.9 on 2026-02-18 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DI4D_app', '0010_merge_20260218_1435'),
        ('DI4D_app', '0012_wopiaccesstoken'),
    ]

    operations = [
    ]
