# Generated by Django 5.2.9 on 2026-02-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DI4D_app', '0012_merge_20260218_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
