# Generated by Django 5.2.9 on 2026-02-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DI4D_app', '0013_merge_0010_merge_20260218_1435_0012_wopiaccesstoken'),
        ('DI4D_app', '0013_news_content'),
    ]

    operations = [
    ]
