# Generated by Django 5.2.9 on 2026-03-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DI4D_app', '0014_merge_20260218_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techtalk',
            name='thubnail',
            field=models.ImageField(upload_to='techtalk/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='techtalk',
            name='videoPath',
            field=models.FileField(upload_to='techtalk/videos/'),
        ),
    ]
