"""
Django settings for DI4D_Portal project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
load_dotenv()
SECRET_KEY = os.getenv("SECRET_KEY_DJANGO")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").strip().lower() in {"1", "true", "yes", "on"}

_allowed_hosts = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    "theme",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'DI4D_app',
    'oidc_provider',
    'mozilla_django_oidc',
]

if DEBUG:
    INSTALLED_APPS.insert(0, "tailwind")
    INSTALLED_APPS.insert(2, "livereload")
    TAILWIND_APP_NAME = "theme"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'DI4D_app.middleware.OIDCLoggingMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    MIDDLEWARE.append('livereload.middleware.LiveReloadScript')

ROOT_URLCONF = 'DI4D_Portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
    { 
        'BACKEND': 'django.template.backends.jinja2.Jinja2', 
        'DIRS': [BASE_DIR / 'jinja_templates'], 
        'APP_DIRS': True, 
        'OPTIONS': { 
            'environment': 'DI4D_Portal.jinja_env.environment', 
        }, 
    }
]

WSGI_APPLICATION = 'DI4D_Portal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Default to SQLite for local development. Use PostgreSQL in production by setting DB_ENGINE=postgres

DB_ENGINE = os.getenv("DB_ENGINE", "sqlite").lower()

if DB_ENGINE == "postgres":
    # PostgreSQL configuration for production (set via Helm values)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'di4d_db'),
            'USER': os.getenv('POSTGRES_USER', 'di4d'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
            'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
        }
    }
else:
    # SQLite configuration for local development (default)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_USER_MODEL = "DI4D_app.User"

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Media files (Uploaded by users)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Only include theme static in dev mode when tailwind is installed
if DEBUG:
    theme_static = BASE_DIR / "theme" / "static"
    if theme_static.exists():
        STATICFILES_DIRS.append(theme_static)

# Use whitenoise for efficient static file serving
MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# OIDC Provider settings
OIDC_USERINFO = 'DI4D_app.oidc_userinfo'
OIDC_EXTRA_SCOPE_CLAIMS = 'DI4D_app.oidc_claims.OIDCExtraScopeClaims'

# Example: OIDC Provider URLs can be set via env if needed
# When running Keycloak in Docker, use host.docker.internal so the container can reach the host
OIDC_ISSUER = os.getenv('OIDC_ISSUER', 'http://host.docker.internal:8000')

# SMTP settings
EMAIL_BACKEND  = os.getenv("EMAIL_BACKEND")
EMAIL_HOST  = os.getenv("SMTP_HOST")
EMAIL_HOST_USER  = os.getenv("SMTP_USER")
EMAIL_PORT   = os.getenv("SMTP_PORT")
EMAIL_HOST_PASSWORD  = os.getenv("SMTP_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")
EMAIL_USE_TLS = True

# OIDC Client settings for Keycloak SSO
OIDC_RP_CLIENT_ID = os.getenv('OIDC_RP_CLIENT_ID', 'django-client-id')
OIDC_RP_CLIENT_SECRET = os.getenv('OIDC_RP_CLIENT_SECRET', 'django-client-secret')
OIDC_OP_AUTHORIZATION_ENDPOINT = os.getenv('OIDC_OP_AUTHORIZATION_ENDPOINT', 'http://localhost:8080/realms/di4d/protocol/openid-connect/auth')
OIDC_OP_TOKEN_ENDPOINT = os.getenv('OIDC_OP_TOKEN_ENDPOINT', 'http://localhost:8080/realms/di4d/protocol/openid-connect/token')
OIDC_OP_USER_ENDPOINT = os.getenv('OIDC_OP_USER_ENDPOINT', 'http://localhost:8080/realms/di4d/protocol/openid-connect/userinfo')
OIDC_OP_JWKS_ENDPOINT = os.getenv('OIDC_OP_JWKS_ENDPOINT', 'http://localhost:8080/realms/di4d/protocol/openid-connect/certs')
OIDC_OP_LOGOUT_ENDPOINT = os.getenv('OIDC_OP_LOGOUT_ENDPOINT', 'http://localhost:8080/realms/di4d/protocol/openid-connect/logout')
LOGIN_URL = '/accounts/login/'
LOGOUT_URL = '/oidc/logout/'
# The application uses Keycloak for most logins (OIDC client)
# but the Django OIDC provider needs a local login form at LOGIN_URL


# Basic logging to console for debugging auth flow
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'DI4D_app': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}