"""
Django settings for DI4D_Portal project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import re

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
load_dotenv(BASE_DIR.parent / ".env")
SECRET_KEY = os.getenv("SECRET_KEY_DJANGO")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", os.getenv("DEBUG", "True")).strip().lower() in {"1", "true", "yes", "on"}
USE_S3 = os.getenv("USE_S3", "False").strip().lower() in {"1", "true", "yes", "on"}

_allowed_hosts = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(",") if h.strip()]

_csrf_trusted_origins = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in _csrf_trusted_origins.split(",")
    if o.strip()
]


# Application definition

INSTALLED_APPS = [
    "theme",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'DI4D_app',
    'django_ckeditor_5',
]

if USE_S3 and "storages" not in INSTALLED_APPS:
    INSTALLED_APPS.append("storages")

if DEBUG:
    INSTALLED_APPS.insert(0, "tailwind")
    INSTALLED_APPS.insert(2, "livereload")
    TAILWIND_APP_NAME = "theme"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    MIDDLEWARE.append('livereload.middleware.LiveReloadScript')

ROOT_URLCONF = 'DI4D_Portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
    { 
        'BACKEND': 'django.template.backends.jinja2.Jinja2', 
        'DIRS': [BASE_DIR / 'jinja_templates'], 
        'APP_DIRS': True, 
        'OPTIONS': { 
            'environment': 'DI4D_Portal.jinja_env.environment', 
        }, 
    }
]

WSGI_APPLICATION = 'DI4D_Portal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Default to SQLite for local development. Use PostgreSQL in production by setting DB_ENGINE=postgres

DB_ENGINE = os.getenv("DB_ENGINE", "sqlite").lower()

if DB_ENGINE == "postgres":
    # PostgreSQL configuration for production (set via Helm values)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'di4d_db'),
            'USER': os.getenv('POSTGRES_USER', 'di4d'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
            'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
        }
    }
else:
    # SQLite configuration for local development (default)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_USER_MODEL = "DI4D_app.User"

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

WHITENOISE_MANIFEST_STRICT = os.getenv("WHITENOISE_MANIFEST_STRICT", "False").strip().lower() in {
    "1",
    "true",
    "yes",
    "on",
}

# Media files (Uploaded by users)
if USE_S3:
    AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", "")
    AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", "")
    AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", "")
    AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL", "").strip() or None
    is_r2_endpoint = bool(AWS_S3_ENDPOINT_URL and "r2.cloudflarestorage.com" in AWS_S3_ENDPOINT_URL)
    is_s3_compatible = bool(
        AWS_S3_ENDPOINT_URL
        and "amazonaws.com" not in AWS_S3_ENDPOINT_URL
        and "r2.cloudflarestorage.com" not in AWS_S3_ENDPOINT_URL
    )
    AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "auto" if is_r2_endpoint else "us-east-1")
    _raw_custom_domain = os.getenv("AWS_S3_CUSTOM_DOMAIN", "").strip()
    AWS_S3_CUSTOM_DOMAIN = re.sub(r'^https?://', '', _raw_custom_domain)
    AWS_LOCATION = os.getenv("AWS_LOCATION", "media").strip("/")
    AWS_S3_FILE_OVERWRITE = os.getenv("AWS_S3_FILE_OVERWRITE", "False").strip().lower() in {"1", "true", "yes", "on"}
    AWS_QUERYSTRING_AUTH = os.getenv("AWS_QUERYSTRING_AUTH", "False").strip().lower() in {"1", "true", "yes", "on"}
    AWS_DEFAULT_ACL = None
    AWS_S3_SIGNATURE_VERSION = os.getenv("AWS_S3_SIGNATURE_VERSION", "").strip() or None
    AWS_S3_ADDRESSING_STYLE = os.getenv("AWS_S3_ADDRESSING_STYLE", "").strip() or None

    if is_r2_endpoint:
        AWS_S3_REGION_NAME = "auto"
        AWS_S3_SIGNATURE_VERSION = AWS_S3_SIGNATURE_VERSION or "s3v4"
        AWS_S3_ADDRESSING_STYLE = AWS_S3_ADDRESSING_STYLE or "path"
        if not AWS_S3_CUSTOM_DOMAIN and not AWS_QUERYSTRING_AUTH:
            AWS_QUERYSTRING_AUTH = True

    if is_s3_compatible:
        AWS_S3_SIGNATURE_VERSION = AWS_S3_SIGNATURE_VERSION or "s3v4"
        AWS_S3_ADDRESSING_STYLE = AWS_S3_ADDRESSING_STYLE or "path"

    if not AWS_STORAGE_BUCKET_NAME:
        raise ValueError("USE_S3 is enabled, but AWS_STORAGE_BUCKET_NAME is not set.")

    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
    }

    if AWS_S3_CUSTOM_DOMAIN:
        media_base = f"https://{AWS_S3_CUSTOM_DOMAIN}"
    elif AWS_S3_ENDPOINT_URL:
        media_base = AWS_S3_ENDPOINT_URL.rstrip("/")
    else:
        media_base = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"

    MEDIA_URL = f"{media_base}/{AWS_LOCATION}/" if AWS_LOCATION else f"{media_base}/"
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
# CKEditor configuration

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading','bold','italic','link','bulletedList','numberedList','blockQuote','imageUpload','insertTable','undo','redo'],
        'height': 400,
        'contentCss': ['/static/news.css'],
        'heading':{
            'options': [
                {'model': 'paragraph',       'title': 'Paragraph',  'class': 'ck-heading_paragraph'},
                {'model': 'heading1',         'view': 'h2',          'title': 'Title',     'class': 'ck-heading_heading1'},
                {'model': 'heading2',         'view': 'h3',          'title': 'Subtitle',  'class': 'ck-heading_heading2'},
                {'model': 'heading3',         'view': 'h4',          'title': 'Heading 3', 'class': 'ck-heading_heading3'},
            ]
        },
        'removePlugins': ['WordCount','CKBox','CKFinderUploadAdapter','EasyImage','CloudServices'],
    }
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Only include theme static in dev mode when tailwind is installed
if DEBUG:
    theme_static = BASE_DIR / "theme" / "static"
    if theme_static.exists():
        STATICFILES_DIRS.append(theme_static)

# Use whitenoise for efficient static file serving
MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SMTP settings
EMAIL_BACKEND  = os.getenv("EMAIL_BACKEND")
EMAIL_HOST  = os.getenv("SMTP_HOST")
EMAIL_HOST_USER  = os.getenv("SMTP_USER")
EMAIL_PORT   = os.getenv("SMTP_PORT")
EMAIL_HOST_PASSWORD  = os.getenv("SMTP_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")
EMAIL_USE_TLS = True

_log_level = os.getenv("DJANGO_LOG_LEVEL", "INFO").upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": _log_level,
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.security.csrf": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

COLLABORA_CODE_URL = os.getenv('COLLABORA_CODE_URL', 'https://localhost:9980').strip()
COLLABORA_INSECURE_SKIP_VERIFY = os.getenv('COLLABORA_INSECURE_SKIP_VERIFY', 'True').strip().lower() in {'1', 'true', 'yes', 'on'}
WOPI_TOKEN_TTL_SECONDS = int(os.getenv('WOPI_TOKEN_TTL_SECONDS', '900'))
WOPI_BASE_URL = os.getenv('WOPI_BASE_URL', '').strip()