{{- if and .Values.collabora.enabled (not .Values.collabora.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "di4d.fullname" . }}-collabora-auth
  labels:
    {{- include "di4d.labels" . | nindent 4 }}
    app.kubernetes.io/component: collabora
type: Opaque
stringData:
  username: {{ .Values.collabora.auth.username | quote }}
  password: {{ .Values.collabora.auth.password | quote }}
{{- end }}
