apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "di4d.fullname" . }}
  labels:
    {{- include "di4d.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "di4d.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "di4d.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "di4d.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
            - name: POSTGRES_HOST
              value: "{{ $.Release.Name }}-postgresql"
            {{- if $.Values.collabora.enabled }}
            {{- $defaultCollaboraUrl := printf "https://%s-collabora:%v" (include "di4d.fullname" $) $.Values.collabora.service.port }}
            {{- if and $.Values.collabora.ingress.enabled $.Values.collabora.ingress.host }}
            {{- $defaultCollaboraUrl = printf "https://%s" $.Values.collabora.ingress.host }}
            {{- end }}
            - name: COLLABORA_CODE_URL
              value: {{ default $defaultCollaboraUrl $.Values.collabora.appEnv.collaboraCodeUrl | quote }}
            - name: COLLABORA_INSECURE_SKIP_VERIFY
              value: {{ $.Values.collabora.appEnv.insecureSkipVerify | quote }}
            - name: WOPI_TOKEN_TTL_SECONDS
              value: {{ $.Values.collabora.appEnv.wopiTokenTtlSeconds | quote }}
            {{- if $.Values.collabora.appEnv.wopiBaseUrl }}
            - name: WOPI_BASE_URL
              value: {{ $.Values.collabora.appEnv.wopiBaseUrl | quote }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
